<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP-PC" ignored="2" name="TestGp(failed)" tests="2" failures="1" timestamp="26 Jun 2021 14:52:14 GMT" time="0.075" errors="0">
  <testcase name="abc" time="0.03" classname="group.Groupping">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.fail(Assert.java:53)
at group.Groupping.abc(Groupping.java:14)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- abc -->
  <testcase name="ghi" time="0.0" classname="group.Groupping">
    <skipped/>
  </testcase> <!-- ghi -->
  <testcase name="mno" time="0.0" classname="group.Groupping">
    <ignored/>
  </testcase> <!-- mno -->
  <testcase name="def" time="0.0" classname="group.Groupping">
    <ignored/>
  </testcase> <!-- def -->
</testsuite> <!-- TestGp(failed) -->
